all: grimGen grimValidator pearGen pearVal shandomGen shandomVal trickGen trickVal sneetchesVal sneetchesGen

grimGen: grimGen.cpp
	g++ -o grimGen grimGen.cpp

grimValidator: grimValidator.cpp
	g++ -o grimValidator grimValidator.cpp

pearGen: pearGen.cpp
	g++ -o pearGen pearGen.cpp

pearVal: pearVal.cpp
	g++ -o pearVal pearVal.cpp

shandomGen: shandomGen.cpp
	g++ -o shandomGen shandomGen.cpp

shandomVal: shandomVal.cpp
	g++ -o shandomVal shandomVal.cpp

trickGen: trickGen.cpp
	g++ -o trickGen trickGen.cpp

trickVal: trickVal.cpp
	g++ -o trickVal trickVal.cpp

sneetchesVal: sneetchesVal.cpp
	g++ -o sneetchesVal sneetchesVal.cpp

sneetchesGen: sneetchesGen.cpp
	g++ -o sneetchesGen sneetchesGen.cpp


